import { useState, useEffect } from 'react'
import type { ReactNode } from 'react'
import { cn } from '../../utils/cn'
import { PrimaryBtn } from '../common/Button'
import { Tag } from '../common/Tag'
import { EXPORT_FORMATS, EXPORT_THEMES } from '../../data/exportOptions'
import { useBuilder } from '../../context/BuilderContext'
import type { BuilderState, PortfolioResult } from '../../types'

// ── Helpers ───────────────────────────────────────────────────────────────────

const DISABLED_FORMATS = ['pdf', 'notion', 'vercel'] as const

function capitalize(s: string) {
  return s.charAt(0).toUpperCase() + s.slice(1)
}

function generateMarkdown(state: BuilderState, _result: PortfolioResult | null): string {
  const { profile, projects, stack, about } = state
  const stackEntries = (Object.entries(stack) as Array<[string, string[]]>).filter(([, v]) => v.length > 0)
  const lines: string[] = []

  if (profile.name) {
    lines.push(`# ${profile.name}${profile.role ? ` — ${profile.role}` : ''}`)
  }
  if (profile.location) lines.push(`\n📍 ${profile.location}`)
  if (profile.bio) lines.push(`\n> ${profile.bio}`)

  if (about.intro || about.career || about.goals) {
    lines.push('\n---\n\n## About\n')
    if (about.intro) lines.push(about.intro)
    if (about.career) lines.push(`\n${about.career}`)
    if (about.goals) lines.push(`\n${about.goals}`)
  }

  if (stackEntries.length > 0) {
    lines.push('\n---\n\n## Tech Stack\n')
    stackEntries.forEach(([k, v]) => {
      lines.push(`**${capitalize(k)}**: ${v.join(', ')}  `)
    })
  }

  if (projects.length > 0) {
    lines.push('\n---\n\n## Projects\n')
    projects.forEach((p) => {
      lines.push(`### ${p.title || '프로젝트'}${p.role ? ` — ${p.role}` : ''}`)
      if (p.desc) lines.push(p.desc)
      const linkParts: string[] = []
      if (p.github) linkParts.push(`🔗 [${p.github}](https://${p.github.replace(/^https?:\/\//, '')})`)
      if (p.deploy) linkParts.push(`🌐 [${p.deploy}](https://${p.deploy.replace(/^https?:\/\//, '')})`)
      if (linkParts.length) lines.push(linkParts.join(' · '))
      lines.push('')
    })
  }

  lines.push('---\n\n*Generated by [Cofolio](https://cofolio.app)*')
  return lines.join('\n')
}

function downloadHtml(state: BuilderState, portfolioName: string, theme: string): void {
  const { profile, projects, stack, about } = state
  const stackEntries = (Object.entries(stack) as Array<[string, string[]]>).filter(([, v]) => v.length > 0)
  const isDark = theme !== 'light'
  const bg = isDark ? '#0b0f1d' : '#ffffff'
  const fg = isDark ? '#e2e8f0' : '#1e293b'
  const sub = isDark ? '#94a3b8' : '#64748b'
  const border = isDark ? 'rgba(255,255,255,0.10)' : 'rgba(0,0,0,0.10)'
  const card = isDark ? 'rgba(255,255,255,0.03)' : 'rgba(0,0,0,0.03)'

  const stackHtml = stackEntries.map(([k, v]) =>
    `<div class="sg"><span class="sl">${capitalize(k)}</span>${v.map((t) => `<span class="tag">${t}</span>`).join('')}</div>`
  ).join('')

  const projectsHtml = projects.map((p) => {
    const links = [
      p.github ? `<a href="https://${p.github.replace(/^https?:\/\//, '')}" target="_blank" rel="noreferrer">GitHub →</a>` : '',
      p.deploy ? `<a href="https://${p.deploy.replace(/^https?:\/\//, '')}" target="_blank" rel="noreferrer">배포 →</a>` : '',
    ].filter(Boolean).join('')
    return `<div class="pc">
      <div class="pt">${p.title || '프로젝트'}${p.role ? `<span class="pr">${p.role}</span>` : ''}</div>
      ${p.desc ? `<div class="pd">${p.desc}</div>` : ''}
      ${links ? `<div class="pl">${links}</div>` : ''}
    </div>`
  }).join('')

  const html = `<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>${profile.name || 'Portfolio'} — Cofolio</title>
<style>
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:${bg};color:${fg};line-height:1.6;padding:40px 20px}
.w{max-width:760px;margin:0 auto}
.hd{border-bottom:1px solid ${border};padding-bottom:24px;margin-bottom:32px}
h1{font-size:28px;font-weight:700;margin-bottom:4px}
.rl{color:${sub};font-size:14px;margin-bottom:8px}
.bi{font-size:15px}
h2{font-size:13px;font-weight:600;text-transform:uppercase;letter-spacing:.12em;color:${sub};margin:32px 0 12px}
.at{font-size:14px;line-height:1.8;margin-bottom:8px}
.sg{display:flex;flex-wrap:wrap;align-items:center;gap:8px;margin-bottom:8px}
.sl{font-size:12px;font-weight:600;color:${sub};min-width:80px}
.tag{display:inline-block;border:1px solid ${border};background:${card};padding:2px 10px;border-radius:6px;font-size:12px;font-family:monospace}
.pc{border:1px solid ${border};background:${card};border-radius:12px;padding:20px;margin-bottom:12px}
.pt{font-size:16px;font-weight:600;margin-bottom:6px}
.pr{display:inline-block;font-size:11px;font-weight:500;border:1px solid ${border};padding:1px 8px;border-radius:999px;margin-left:8px;vertical-align:middle}
.pd{font-size:13px;color:${sub};margin-bottom:10px;line-height:1.6}
.pl{display:flex;gap:12px}
.pl a{font-size:13px;color:#7c3aed;text-decoration:none}
.pl a:hover{text-decoration:underline}
.ft{margin-top:48px;padding-top:16px;border-top:1px solid ${border};font-size:12px;color:${sub};text-align:center}
.ft a{color:#7c3aed;text-decoration:none}
</style>
</head>
<body>
<div class="w">
  <div class="hd">
    <h1>${profile.name || 'Portfolio'}</h1>
    <div class="rl">${[profile.role, profile.location].filter(Boolean).join(' · ')}</div>
    ${profile.bio ? `<div class="bi">${profile.bio}</div>` : ''}
  </div>
  ${about.intro || about.career || about.goals ? `<h2>About</h2>
    ${about.intro ? `<div class="at">${about.intro}</div>` : ''}
    ${about.career ? `<div class="at">${about.career}</div>` : ''}
    ${about.goals ? `<div class="at">${about.goals}</div>` : ''}` : ''}
  ${stackEntries.length ? `<h2>Tech Stack</h2>${stackHtml}` : ''}
  ${projects.length ? `<h2>Projects</h2>${projectsHtml}` : ''}
  <div class="ft">Generated by <a href="https://cofolio.app">Cofolio</a></div>
</div>
</body>
</html>`

  const blob = new Blob([html], { type: 'text/html;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${(portfolioName || 'portfolio').replace(/\s+/g, '-')}-${theme}.html`
  document.body.appendChild(a)
  a.click()
  setTimeout(() => { document.body.removeChild(a); URL.revokeObjectURL(url) }, 100)
}

// ── Icons ─────────────────────────────────────────────────────────────────────

const FORMAT_ICONS: Record<string, ReactNode> = {
  html: (
    <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round">
      <path d="m9 9-3 3 3 3M15 9l3 3-3 3M14 7l-4 10" />
      <rect x="3" y="3" width="18" height="18" rx="2" />
    </svg>
  ),
  pdf: (
    <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round">
      <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
      <path d="M14 2v6h6M9 13h6M9 17h4" />
    </svg>
  ),
  md: (
    <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round">
      <rect x="3" y="5" width="18" height="14" rx="2" />
      <path d="M7 15V9l3 3 3-3v6M16 9v6M14 13l2 2 2-2" />
    </svg>
  ),
  notion: (
    <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round">
      <rect x="4" y="3" width="16" height="18" rx="1.5"/>
      <path d="M8 7h8M8 11h8M8 15h5"/>
    </svg>
  ),
  vercel: (
    <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round">
      <path d="M12 3 22 20H2L12 3z"/>
    </svg>
  ),
}

// ── Component ─────────────────────────────────────────────────────────────────

interface Props {
  isOpen: boolean
  onClose: () => void
  portfolioName?: string
}

export function ExportModal({ isOpen, onClose, portfolioName = '포트폴리오' }: Props) {
  const { state, result } = useBuilder()
  const [format, setFormat] = useState('html')
  const [theme, setTheme] = useState('dark')
  const [busy, setBusy] = useState(false)
  const [done, setDone] = useState<{ title: string; sub: string } | null>(null)
  const [exportError, setExportError] = useState<string | null>(null)

  useEffect(() => {
    if (isOpen) { setBusy(false); setDone(null); setExportError(null) }
  }, [isOpen])

  useEffect(() => {
    if (!isOpen) return
    const prev = document.body.style.overflow
    document.body.style.overflow = 'hidden'
    const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') onClose() }
    window.addEventListener('keydown', onKey)
    return () => { document.body.style.overflow = prev; window.removeEventListener('keydown', onKey) }
  }, [isOpen, onClose])

  if (!isOpen) return null

  const isDisabled = DISABLED_FORMATS.includes(format as typeof DISABLED_FORMATS[number])

  const handleExport = async () => {
    if (isDisabled || busy) return
    setBusy(true)
    setExportError(null)

    try {
      if (format === 'md') {
        const markdown = generateMarkdown(state, result)
        await navigator.clipboard.writeText(markdown)
        setDone({ title: 'Markdown이 복사되었습니다', sub: 'GitHub 프로필 README에 붙여넣어 보세요' })
      } else if (format === 'html') {
        downloadHtml(state, portfolioName, theme)
        setDone({ title: 'HTML 다운로드를 시작했어요', sub: `${portfolioName}-${theme}.html` })
      }
    } catch {
      setExportError('클립보드 복사에 실패했습니다. 브라우저 권한을 확인하거나 직접 복사해주세요.')
    } finally {
      setBusy(false)
    }
  }

  const selectedFormat = EXPORT_FORMATS.find((f) => f.id === format)
  const selectedTheme = EXPORT_THEMES.find((t) => t.id === theme)

  const actionLabel = () => {
    if (isDisabled) return '준비 중'
    if (format === 'md') return 'Markdown 복사'
    return '다운로드'
  }

  return (
    <div
      className="fixed inset-0 z-[80] flex items-center justify-center px-4"
      style={{ animation: 'fadeIn .2s ease' }}
      onClick={onClose}
    >
      <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" />
      <div
        onClick={(e) => e.stopPropagation()}
        className="relative w-full max-w-[640px] rounded-2xl glass-strong overflow-hidden ring-grad"
        style={{ animation: 'popIn .3s cubic-bezier(.2,.7,.2,1)' }}
      >
        {/* Header */}
        <div className="px-6 pt-5 pb-4 border-b border-white/8 flex items-start justify-between gap-3">
          <div>
            <div className="text-[11px] uppercase tracking-[0.18em] text-violet-300/90">EXPORT</div>
            <div className="mt-1 text-[20px] font-semibold tracking-tight">포트폴리오 내보내기</div>
            <div className="mt-1 text-[12.5px] text-slate-400">형식과 테마를 선택하세요. 언제든 다시 만들 수 있어요.</div>
          </div>
          <button
            onClick={onClose}
            className="rounded-lg border border-white/10 bg-white/[0.04] h-8 w-8 grid place-items-center text-slate-300 hover:bg-white/[0.08]"
            aria-label="닫기"
          >
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M18 6L6 18M6 6l12 12"/></svg>
          </button>
        </div>

        {/* Body */}
        {!done ? (
          <div className="px-6 py-5 space-y-5">
            {/* Format grid */}
            <div>
              <div className="text-[11px] uppercase tracking-[0.16em] text-slate-400 mb-2.5">형식</div>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
                {EXPORT_FORMATS.map((f) => {
                  const sel = format === f.id
                  const dis = DISABLED_FORMATS.includes(f.id as typeof DISABLED_FORMATS[number])
                  return (
                    <button
                      key={f.id}
                      onClick={() => !dis && setFormat(f.id)}
                      disabled={dis}
                      className={cn(
                        'text-left rounded-xl border p-3.5 transition flex items-start gap-3',
                        dis
                          ? 'border-white/8 bg-white/[0.015] opacity-50 cursor-not-allowed'
                          : sel
                          ? 'border-violet-400/60 bg-violet-500/[0.08] ring-1 ring-violet-400/30'
                          : 'border-white/10 bg-white/[0.03] hover:bg-white/[0.06]'
                      )}
                    >
                      <div className={cn(
                        'grid h-9 w-9 place-items-center rounded-lg shrink-0',
                        sel && !dis ? 'bg-gradient-to-br from-violet-500/30 to-cyan-500/20 text-violet-100' : 'bg-white/[0.04] text-slate-300'
                      )}>
                        {FORMAT_ICONS[f.id]}
                      </div>
                      <div className="min-w-0 flex-1">
                        <div className="flex items-center gap-2">
                          <div className="text-[13.5px] font-semibold text-slate-100">{f.title}</div>
                          {dis
                            ? <Tag tone="violet">준비 중</Tag>
                            : f.badge
                            ? <Tag tone="violet">{f.badge}</Tag>
                            : null}
                        </div>
                        <div className="mt-0.5 text-[11.5px] text-slate-400 leading-snug">{f.desc}</div>
                      </div>
                      <div className={cn('mt-0.5 h-4 w-4 shrink-0 rounded-full border', sel && !dis ? 'border-violet-400 bg-violet-400' : 'border-white/20')}>
                        {sel && !dis && (
                          <svg viewBox="0 0 16 16" className="h-full w-full text-white">
                            <path d="M3.5 8.5l3 3 6-7" stroke="currentColor" strokeWidth="2" fill="none" strokeLinecap="round" strokeLinejoin="round"/>
                          </svg>
                        )}
                      </div>
                    </button>
                  )
                })}
              </div>
            </div>

            {/* Theme picker */}
            <div>
              <div className="text-[11px] uppercase tracking-[0.16em] text-slate-400 mb-2.5">테마</div>
              <div className="grid grid-cols-3 gap-2.5">
                {EXPORT_THEMES.map((t) => {
                  const sel = theme === t.id
                  return (
                    <button
                      key={t.id}
                      onClick={() => setTheme(t.id)}
                      className={cn(
                        'rounded-xl border p-3 text-left transition',
                        sel ? 'border-violet-400/60 bg-violet-500/[0.08] ring-1 ring-violet-400/30' : 'border-white/10 bg-white/[0.03] hover:bg-white/[0.06]'
                      )}
                    >
                      <div className="h-12 w-full rounded-lg border border-white/10" style={{ background: t.swatch }} />
                      <div className="mt-2 text-[12.5px] font-semibold text-slate-100">{t.title}</div>
                      <div className="text-[10.5px] text-slate-400 leading-snug">{t.sub}</div>
                    </button>
                  )
                })}
              </div>
            </div>

            {/* Error */}
            {exportError && (
              <div className="rounded-xl border border-red-400/30 bg-red-500/10 px-3.5 py-2.5 text-[12.5px] text-red-300">
                {exportError}
              </div>
            )}

            {/* Info note */}
            <div className="rounded-xl border border-white/8 bg-white/[0.03] px-3.5 py-2.5 flex items-center gap-2.5">
              <div className="h-7 w-7 grid place-items-center rounded-md bg-violet-500/15 text-violet-200">
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><circle cx="12" cy="12" r="10"/><path d="M12 8v5M12 16h.01"/></svg>
              </div>
              <div className="text-[11.5px] text-slate-400 leading-snug">
                내보낸 결과물에는 Cofolio 워터마크가 포함되지 않습니다. Pro 플랜에서는 커스텀 도메인 연결도 가능해요.
              </div>
            </div>
          </div>
        ) : (
          <div className="px-6 py-8 text-center">
            <div className="mx-auto h-14 w-14 grid place-items-center rounded-full bg-gradient-to-br from-emerald-500/30 to-cyan-500/20 ring-1 ring-emerald-400/40">
              <svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="#34d399" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round"><path d="M5 12.5l4.5 4.5L19 7"/></svg>
            </div>
            <div className="mt-3 text-[18px] font-semibold tracking-tight">{done.title}</div>
            <div className="mt-1 text-[12.5px] text-slate-400 break-all">{done.sub}</div>
          </div>
        )}

        {/* Footer */}
        <div className="border-t border-white/8 bg-white/[0.02] px-6 py-3.5 flex items-center justify-between gap-3">
          <div className="text-[11.5px] text-slate-500">
            {!done && <>선택: <span className="text-slate-300">{selectedFormat?.title}</span> · <span className="text-slate-300">{selectedTheme?.title}</span></>}
            {done && <>완료 — 다른 형식으로도 내보낼 수 있어요.</>}
          </div>
          <div className="flex items-center gap-2">
            {!done ? (
              <>
                <button onClick={onClose} className="rounded-lg border border-white/10 bg-white/[0.04] px-3.5 h-9 text-[12.5px] text-slate-200 hover:bg-white/[0.08]">취소</button>
                <PrimaryBtn size="sm" onClick={handleExport} disabled={busy || isDisabled}>
                  {busy ? (
                    <>
                      <svg width="14" height="14" viewBox="0 0 24 24" className="animate-spin">
                        <circle cx="12" cy="12" r="9" stroke="currentColor" strokeWidth="2.5" fill="none" strokeDasharray="42" strokeDashoffset="20"/>
                      </svg>
                      처리 중…
                    </>
                  ) : (
                    <>
                      {actionLabel()}
                      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M5 12h14M13 6l6 6-6 6"/></svg>
                    </>
                  )}
                </PrimaryBtn>
              </>
            ) : (
              <>
                <button onClick={() => { setDone(null); setExportError(null) }} className="rounded-lg border border-white/10 bg-white/[0.04] px-3.5 h-9 text-[12.5px] text-slate-200 hover:bg-white/[0.08]">다시 내보내기</button>
                <PrimaryBtn size="sm" onClick={onClose}>완료</PrimaryBtn>
              </>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}
